NewsApp.UI/Controllers/TagController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NewsApp.Api.Client;
using NewsApp.Api.Client.Refit.Dependency;
using NewsApp.UI.Models.ViewModel;
using System.Collections.Generic;

namespace NewsApp.UI.Controllers
{
    public class TagController : Controller
    {
        private readonly IMapper _mapper;
        public TagController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var response = RefitApiServiceDependency.TagApi.List(new ListTagQueryRequest
            {
            });
            if (response.Exception == null)
            {
                var result = _mapper.Map<List<ListTagQueryResponseViewModel>>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateTagCommandRequestViewModel createTagCommandRequestViewModel)
        {
            var result = _mapper.Map<CreateTagCommandRequest>(createTagCommandRequestViewModel);
            var response = RefitApiServiceDependency.TagApi.Post(result);
            if (response.Exception == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Edit(string id)
        {
            var responseEdit = RefitApiServiceDependency.TagApi.Get(id);

            if (responseEdit.Exception == null)
            {
                var result = _mapper.Map<TagQueryResponseViewModel>(responseEdit.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }


        }
        [HttpPost]
        public IActionResult Edit(UpdateTagCommandRequestViewModel updateTagCommandRequestViewModel)
        {
            var result = _mapper.Map<UpdateTagCommandRequest>(updateTagCommandRequestViewModel);
            var responseUpdate = RefitApiServiceDependency.TagApi.Put(result);

            TempData["Message"] = updateTagCommandRequestViewModel.Id + "'li kategori güncellendi .";

            var responseList = RefitApiServiceDependency.TagApi.List(new ListTagQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listTagQueryResponseViewModel = _mapper.Map<List<ListTagQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/Tag/Index.cshtml", listTagQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Remove(string id)
        {
            var responseDelete = RefitApiServiceDependency.TagApi.Delete(id);

            TempData["Message"] = id + "'li kategori silindi .";

            var responseList = RefitApiServiceDependency.TagApi.List(new ListTagQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listTagQueryResponseViewModel = _mapper.Map<List<ListTagQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/Tag/Index.cshtml", listTagQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

NewsApp.UI/Views/Tag/Create.cshtml
@model CreateTagCommandRequestViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "Tag", FormMethod.Post))
{
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Tag Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Tag Add</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Tag Name</label>
                                @Html.TextBoxFor(m => m.Name)
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Display Order</label>
                                @Html.TextBoxFor(m => m.DisplayOrder)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Create new Tag" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>


}

NewsApp.UI/Views/Tag/Edit.cshtml
@model TagQueryResponseViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" action="@Url.Action("Edit", "Tag")">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Tag Edit</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Tag Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Tag Id</label>
                                @Html.TextBoxFor(m => m.Id, new { @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                <label for="inputName">Tag Name</label>
                                @Html.TextBoxFor(m => m.Name)
                            </div>
                            <div class="form-group">
                                <label for="inputClientCompany">Url</label>
                                @Html.TextBoxFor(m => m.DisplayOrder)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Edit Tag" class="btn btn-success float-right">
                </div>
            </div>
        </section>

    </div>
</form>

NewsApp.UI/Views/Tag/Index.cshtml
@model IEnumerable<ListTagQueryResponseViewModel>
@{
    ViewData["Title"] = "Tag";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Message"] != null)
{
    <script>
        alert('@Html.Raw(TempData["Message"])')
    </script>
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header btn-success btn-lg">
                            <a href="@Url.Action("Create", "Tag")">Tag Create </a>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>DisplayOrder</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Name</td>
                                            <td>@item.DisplayOrder</td>
                                            <td><a href="@Url.Action("Edit", "Tag",new { id = item.Id})">Tag Update </a></td>
                                            <td><a href="@Url.Action("Remove", "Tag",new { id = item.Id})">Tag Delete </a></td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>