NewsApp.UI/Controllers/ChannelController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NewsApp.Api.Client;
using NewsApp.Api.Client.Refit.Dependency;
using NewsApp.UI.Models.ViewModel;
using System.Collections.Generic;

namespace NewsApp.UI.Controllers
{
    public class ChannelController : Controller
    {
        private readonly IMapper _mapper;
        public ChannelController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var response = RefitApiServiceDependency.ChannelApi.List(new ListChannelQueryRequest
            {
            });
            if (response.Exception == null)
            {
                var result = _mapper.Map<List<ListChannelQueryResponseViewModel>>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateChannelCommandRequestViewModel createChannelCommandRequestViewModel)
        {
            var resultRequest = _mapper.Map<CreateChannelCommandRequest>(createChannelCommandRequestViewModel);
            var response = RefitApiServiceDependency.ChannelApi.Post(resultRequest);
            if (response.Exception == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Edit(string id)
        {
            var response = RefitApiServiceDependency.ChannelApi.Get(id);
            if (response.Exception == null)
            {
                var result = _mapper.Map<ChannelQueryResponseViewModel>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        public IActionResult Edit(UpdateChannelCommandRequestViewModel updateChannelCommandRequestViewModel)
        {
            var resultRequest = _mapper.Map<UpdateChannelCommandRequest>(updateChannelCommandRequestViewModel);
            var response = RefitApiServiceDependency.ChannelApi.Put(resultRequest);
            if (response.Exception == null)
            {
                TempData["Message"] = updateChannelCommandRequestViewModel.Id + "'li channel güncellendi .";
                var responseList = RefitApiServiceDependency.ChannelApi.List(new ListChannelQueryRequest
                {
                });
                if (responseList.Exception == null)
                {
                    var result = _mapper.Map<List<ListChannelQueryResponseViewModel>>(responseList.Result);
                    return View("~/Views/Channel/Index.cshtml", result);
                }
                else
                {
                    return RedirectToAction("Error");
                }

            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Remove(string id)
        {
            var response = RefitApiServiceDependency.ChannelApi.Delete(id);
            if (response.Exception == null)
            {
                TempData["Message"] = id + "li channel silindi .";
                var responseList = RefitApiServiceDependency.ChannelApi.List(new ListChannelQueryRequest
                {
                });
                if (responseList.Exception == null)
                {
                    var result = _mapper.Map<List<ListChannelQueryResponseViewModel>>(responseList.Result);
                    return View("~/Views/Channel/Index.cshtml", result);
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

NewsApp.UI/Views/Channel/Create.cshtml
@model CreateChannelCommandRequestViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Channel", FormMethod.Post))
{
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Channel Add</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Channel Name</label>
                                @Html.TextBoxFor(m => m.Name)
                            </div>
                            <div class="form-group">
                                <label for="inputClientCompany">Url</label>
                                @Html.TextBoxFor(m => m.Url)
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Image Path</label>
                                @Html.TextBoxFor(m => m.ImagePath)
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Display Order</label>
                                @Html.TextBoxFor(m => m.DisplayOrder)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Create new Channel" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>


}

NewsApp.UI/Views/Channel/Edit.cshtml
@model ChannelQueryResponseViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" action="@Url.Action("Edit", "Channel")">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Channel Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Channel Id</label>
                                @Html.TextBoxFor(m => m.Id, new { @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                <label for="inputName">Channel Name</label>
                                @Html.TextBoxFor(m => m.Name)
                            </div>
                            <div class="form-group">
                                <label for="inputClientCompany">Url</label>
                                @Html.TextBoxFor(m => m.Url)
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Image Path</label>
                                @Html.TextBoxFor(m => m.ImagePath)
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Display Order</label>
                                @Html.TextBoxFor(m => m.DisplayOrder)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Edit Channel" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>
</form>

NewsApp.UI/Views/Channel/Index.cshtml
@model IEnumerable<ListChannelQueryResponseViewModel>
@{
    ViewData["Title"] = "Channel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Message"] != null)
{
    <script>
        alert('@Html.Raw(TempData["Message"])')
    </script>
}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="@Url.Action("Create", "Channel")">Channel Create </a>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Url</th>
                                        <th>ImagePath</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Name</td>
                                            <td>@item.Url</td>
                                            <td>@item.ImagePath</td>
                                            <td><a href="@Url.Action("Edit", "Channel",new { id = item.Id})">Channel Update </a></td>
                                            <td><a href="@Url.Action("Remove", "Channel",new { id = item.Id})">Channel Delete </a></td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>