NewsApp.UI/Controllers/NewsNewsTagMapController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsApp.Api.Client;
using NewsApp.Api.Client.Refit.Dependency;
using NewsApp.UI.Models.ViewModel;
using System.Collections.Generic;
using System.Linq;

namespace NewsApp.UI.Controllers
{
    public class NewsNewsTagMapController : Controller
    {
        private readonly IMapper _mapper;
        public NewsNewsTagMapController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var response = RefitApiServiceDependency.NewsNewsTagMapApi.List(new ListNewsNewsTagMapQueryRequest
            {
            });
            if (response.Exception == null)
            {
                var result = _mapper.Map<List<ListNewsNewsTagMapQueryResponseViewModel>>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Create()
        {
            var model = new CreateNewsNewsTagMapCommandRequestViewModel()
            {
                NewsIds = PrepareBookerDestinationNews(),
                NewsTagIds = PrepareBookerDestinationNewsTag()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(CreateNewsNewsTagMapCommandRequestViewModel createNewsNewsTagMapCommandRequestViewModel)
        {
            var result = _mapper.Map<CreateNewsNewsTagMapCommandRequest>(createNewsNewsTagMapCommandRequestViewModel);
            var response = RefitApiServiceDependency.NewsNewsTagMapApi.Post(result);
            if (response.Exception == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Edit(string id)
        {
            var responseEdit = RefitApiServiceDependency.NewsNewsTagMapApi.Get(id);

            if (responseEdit.Exception == null)
            {
                var result = _mapper.Map<NewsNewsTagMapQueryResponseViewModel>(responseEdit.Result);
                result.NewsIds = PrepareBookerDestinationNews();
                result.NewsTagIds = PrepareBookerDestinationNewsTag();
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }


        }
        [HttpPost]
        public IActionResult Edit(UpdateNewsNewsTagMapCommandRequestViewModel updateNewsNewsTagMapCommandRequestViewModel)
        {
            var result = _mapper.Map<UpdateNewsNewsTagMapCommandRequest>(updateNewsNewsTagMapCommandRequestViewModel);
            var responseUpdate = RefitApiServiceDependency.NewsNewsTagMapApi.Put(result);

            TempData["Message"] = updateNewsNewsTagMapCommandRequestViewModel.Id + "'li kategori güncellendi .";

            var responseList = RefitApiServiceDependency.NewsNewsTagMapApi.List(new ListNewsNewsTagMapQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listNewsNewsTagMapQueryResponseViewModel = _mapper.Map<List<ListNewsNewsTagMapQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/NewsNewsTagMap/Index.cshtml", listNewsNewsTagMapQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Remove(string id)
        {
            var responseDelete = RefitApiServiceDependency.NewsNewsTagMapApi.Delete(id);

            TempData["Message"] = id + "'li kategori silindi .";

            var responseList = RefitApiServiceDependency.NewsNewsTagMapApi.List(new ListNewsNewsTagMapQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listNewsNewsTagMapQueryResponseViewModel = _mapper.Map<List<ListNewsNewsTagMapQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/NewsNewsTagMap/Index.cshtml", listNewsNewsTagMapQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        private List<SelectListItem> PrepareBookerDestinationNews()
        {
            List<string> channelCategoryMapIds = new List<string> { "62058959e660d4a0d70ad79f" };

            ListNewsQueryRequest listNewsQueryRequest = new ListNewsQueryRequest()
            {
                ChannelCategoryMapIds = channelCategoryMapIds
            };
            var bookerDestination = RefitApiServiceDependency.NewsApi.List(listNewsQueryRequest);
            var typeSelectListItems = bookerDestination.Result.ToList().Select(x => new SelectListItem { Text = x.Title, Value = x.Id.ToString() }).ToList();
            return typeSelectListItems;
        }
        private List<SelectListItem> PrepareBookerDestinationNewsTag()
        {
            var bookerDestination = RefitApiServiceDependency.TagApi.List(new ListTagQueryRequest
            {
            });
            var typeSelectListItems = bookerDestination.Result.ToList().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            return typeSelectListItems;
        }
    }
}

NewsApp.UI/Views/NewsNewsTagMap/Create.cshtml
@model CreateNewsNewsTagMapCommandRequestViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "NewsNewsTagMap", FormMethod.Post))
{
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">NewsNewsTagMap Add</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">

                            <div class="col-lg-6">
                                @Html.Label("NewsId")
                                @Html.DropDownListFor(model => model.NewsId, Model.NewsIds, "--Select an Type--",
                                new { type = "text", @class = "form-control", required = "required", @placeholder = "NewsId" })
                                @Html.ValidationMessageFor(c => c.NewsIds.First().Value)
                            </div>
                            <div class="col-lg-6">
                                @Html.Label("TagId")
                                @Html.DropDownListFor(model => model.TagId, Model.NewsTagIds, "--Select an Type--",
                                new { type = "text", @class = "form-control", required = "required", @placeholder = "NewsId" })
                                @Html.ValidationMessageFor(c => c.NewsIds.First().Value)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Create new NewsNewsTagMap" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>


}

NewsApp.UI/Views/NewsNewsTagMap/Edit.cshtml
@model NewsNewsTagMapQueryResponseViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" action="@Url.Action("Edit", "NewsNewsTagMap")">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">NewsNewsTagMap Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col-lg-6">
                                @Html.Label("NewsId")
                                @Html.DropDownListFor(model => model.NewsId, Model.NewsIds, "--Select an Type--",
                                new { type = "text", @class = "form-control", required = "required", @placeholder = "NewsId" })
                                @Html.ValidationMessageFor(c => c.NewsIds.First().Value)
                            </div>
                            <div class="col-lg-6">
                                @Html.Label("TagId")
                                @Html.DropDownListFor(model => model.TagId, Model.NewsTagIds, "--Select an Type--",
                                new { type = "text", @class = "form-control", required = "required", @placeholder = "NewsId" })
                                @Html.ValidationMessageFor(c => c.NewsIds.First().Value)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input style="position:center" type="submit" value="Edit" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>
</form>

NewsApp.UI/Views/NewsNewsTagMap/Index.cshtml
@model IEnumerable<ListNewsNewsTagMapQueryResponseViewModel>
@{
    ViewData["Title"] = "NewsNewsTagMap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Message"] != null)
{
    <script>
        alert('@Html.Raw(TempData["Message"])')
    </script>
}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header btn-success btn-lg">
                            <a href="@Url.Action("Create", "NewsNewsTagMap")">NewsNewsTagMap Create </a>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>NewsId</th>
                                        <th>ImagePath</th>
                                        <th>DisplayOrder</th>
                                        <th>CreatedDate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.NewsId</td>
                                            <td>@item.TagId</td>
                                            <td>@item.CreatedDate</td>
                                            <td><a href="@Url.Action("Edit", "NewsNewsTagMap",new { id = item.Id})"> Update </a></td>
                                            <td><a href="@Url.Action("Remove", "NewsNewsTagMap",new { id = item.Id})"> Delete </a></td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>