NewsApp.UI/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NewsApp.Api.Client;
using NewsApp.Api.Client.Refit.Dependency;
using NewsApp.UI.Models.ViewModel;
using System.Collections.Generic;

namespace NewsApp.UI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IMapper _mapper;
        public CategoryController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var response = RefitApiServiceDependency.CategoryApi.List(new ListCategoryQueryRequest
            {
            });
            if (response.Exception == null)
            {
                var result = _mapper.Map<List<ListCategoryQueryResponseViewModel>>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateCategoryCommandRequestViewModel createCategoryCommandRequestViewModel)
        {
            var result = _mapper.Map<CreateCategoryCommandRequest>(createCategoryCommandRequestViewModel);
            var response = RefitApiServiceDependency.CategoryApi.Post(result);
            if (response.Exception == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Edit(string id)
        {
            var responseEdit = RefitApiServiceDependency.CategoryApi.Get(id);

            if (responseEdit.Exception == null)
            {
                var result = _mapper.Map<CategoryQueryResponseViewModel>(responseEdit.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }


        }
        [HttpPost]
        public IActionResult Edit(UpdateCategoryCommandRequestViewModel updateCategoryCommandRequestViewModel)
        {
            var result = _mapper.Map<UpdateCategoryCommandRequest>(updateCategoryCommandRequestViewModel);
            var responseUpdate = RefitApiServiceDependency.CategoryApi.Put(result);

            TempData["Message"] = updateCategoryCommandRequestViewModel.Id + "'li kategori güncellendi .";

            var responseList = RefitApiServiceDependency.CategoryApi.List(new ListCategoryQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listCategoryQueryResponseViewModel = _mapper.Map<List<ListCategoryQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/Category/Index.cshtml", listCategoryQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Remove(string id)
        {
            var responseDelete = RefitApiServiceDependency.CategoryApi.Delete(id);

            TempData["Message"] = id + "'li kategori silindi .";

            var responseList = RefitApiServiceDependency.CategoryApi.List(new ListCategoryQueryRequest
            {
            });

            if (responseList.Exception == null)
            {
                var listCategoryQueryResponseViewModel = _mapper.Map<List<ListCategoryQueryResponseViewModel>>(responseList.Result);
                return View("~/Views/Category/Index.cshtml", listCategoryQueryResponseViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

NewsApp.UI/Controllers/NewsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NewsApp.Api.Client;
using NewsApp.Api.Client.Refit.Dependency;
using NewsApp.UI.Models.ViewModel;
using System.Collections.Generic;

namespace NewsApp.UI.Controllers
{
    public class NewsController : Controller
    {
        private readonly IMapper _mapper;
        public NewsController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            List<string> channelCategoryMapIds = new List<string> { "62058959e660d4a0d70ad79f" };

            ListNewsQueryRequest listNewsQueryRequest = new ListNewsQueryRequest()
            {
                ChannelCategoryMapIds = channelCategoryMapIds
            };
            var response = RefitApiServiceDependency.NewsApi.List(listNewsQueryRequest);
            if (response.Exception == null)
            {
                var result = _mapper.Map<List<ListNewsQueryResponseViewModel>>(response.Result);
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateNewsCommandRequestViewModel createNewsCommandRequestViewModel)
        {
            var resultRequest = _mapper.Map<CreateNewsCommandRequest>(createNewsCommandRequestViewModel);
            var response = RefitApiServiceDependency.NewsApi.Post(resultRequest);
            if (response.Exception == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Edit(string id)
        {
            var response = RefitApiServiceDependency.NewsApi.Get(id);
            if (response.Exception == null)
            {
                var result = response.Result;
                return View(result);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        public IActionResult Edit(UpdateNewsCommandRequestViewModel updateNewsCommandRequestViewModel)
        {
            var resultRequest = _mapper.Map<UpdateNewsCommandRequest>(updateNewsCommandRequestViewModel);
            var response = RefitApiServiceDependency.NewsApi.Put(resultRequest);
            if (response.Exception == null)
            {
                TempData["Message"] = updateNewsCommandRequestViewModel.Id + "'li channel güncellendi .";
                var responseList = RefitApiServiceDependency.NewsApi.List(new ListNewsQueryRequest
                {
                });
                if (responseList.Exception == null)
                {
                    var result = _mapper.Map<List<ListNewsQueryResponseViewModel>>(responseList.Result);
                    return View("~/Views/News/Index.cshtml", result);
                }
                else
                {
                    return RedirectToAction("Error");
                }

            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        public IActionResult Remove(string id)
        {
            var response = RefitApiServiceDependency.NewsApi.Delete(id);
            if (response.Exception == null)
            {
                TempData["Message"] = id + "li channel silindi .";
                var responseList = RefitApiServiceDependency.NewsApi.List(new ListNewsQueryRequest
                {
                });
                if (responseList.Exception == null)
                {
                    var result = _mapper.Map<List<ListNewsQueryResponseViewModel>>(responseList.Result);
                    return View("~/Views/Channel/Index.cshtml", result);
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

NewsApp.UI/Views/News/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" action="@Url.Action("Create", "News")">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Project Add</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Project Name</label>
                                <input type="text" id="inputName" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Project Description</label>
                                <textarea id="inputDescription" class="form-control" rows="4"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select id="inputStatus" class="form-control custom-select">
                                    <option selected disabled>Select one</option>
                                    <option>On Hold</option>
                                    <option>Canceled</option>
                                    <option>Success</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputClientCompany">Client Company</label>
                                <input type="text" id="inputClientCompany" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Project Leader</label>
                                <input type="text" id="inputProjectLeader" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="#" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create new Project" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>
</form>

NewsApp.UI/Views/News/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" action="@Url.Action("Create", "Category")">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Project Add</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Project Add</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">General</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Project Name</label>
                                <input type="text" id="inputName" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Project Description</label>
                                <textarea id="inputDescription" class="form-control" rows="4"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select id="inputStatus" class="form-control custom-select">
                                    <option selected disabled>Select one</option>
                                    <option>On Hold</option>
                                    <option>Canceled</option>
                                    <option>Success</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputClientCompany">Client Company</label>
                                <input type="text" id="inputClientCompany" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputProjectLeader">Project Leader</label>
                                <input type="text" id="inputProjectLeader" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="#" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create new Project" class="btn btn-success float-right">
                </div>
            </div>
        </section>
    </div>
</form>

NewsApp.UI/Views/News/Index.cshtml
@model IEnumerable<ListNewsQueryResponseViewModel>

@{
    ViewData["Title"] = "News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="@Url.Action("Create", "News")">News Create </a>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>DisplayOrder</th>
                                        <th>ProviderNewsId</th>
                                        <th>Link</th>
                                        <th>Language</th>
                                        <th>XmlPath</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Title</td>
                                        @if (item.Description.Length > 20)
                                        {
                                            <td>@item.Description.Substring(0, 20)</td>
                                        }
                                        else
                                        {
                                            <td>@item.Description</td>
                                        }
                                        <td>@item.DisplayOrder</td>
                                        <td>@item.ProviderNewsId</td>
                                        <td>@item.Link</td>
                                        <td>@item.Language</td>
                                        <td>@item.XmlPath</td>
                                        <td><a href="@Url.Action("Edit", "News",new { id = item.Id})">News Update </a></td>
                                        <td><a href="@Url.Action("Remove", "News",new { id = item.Id})">News Delete </a></td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>